### PR TITLE
Fix amd to slim transform when "module" is imported

### PR DESCRIPTION
**Pull request by m-mujica**
Ref: https://github.com/stealjs/steal-tools/issues/845

### CODE REVIEW

**Comment by m-mujica** [comment]
@matthewp something I noticed is that transpile only replace `module` with `stealModule` when it's in a member expression.

So if someone does `module.id` it's but if for some reason they only reference the identifier like 

```js
define(["module"], function(module) {
  doSomething(module);
});
```

the replacement won't happen... 

we should probably make sure all references are replaced, right?
I'm hesitant b/c someone could declare their one `var module = ...`, what do you think?

**Comment by matthewp** [comment]
Yeah, we should make that work too, because done-autorender does pass in the entire `module` object I believe.

**Comment by m-mujica** [comment]
@matthewp this one should be good to go now.

**Comment by m-mujica** [comment]
@matthewp yay, nay?

**Comment by matthewp** [comment]
Oh, I forgot to comment. Yep, looks fine to me.

**Pull request merged**
