### PR TITLE
Add CJS dependencies to the AMD define function

### PR DESCRIPTION
**Pull request by m-mujica**
Related to https://github.com/stealjs/steal-tools/issues/563

This will ensure that dependencies will be loaded when the regular expression based logic used by the steal extensions fail to match the module identifier when the code is minified.

### CODE REVIEW

**Comment by matthewp** [comment]
Just to make sure, this won't affect slim builds because they don't go through this transform, is that right?

**Comment by m-mujica** [comment]
hmm, I think it does affect it, we don't a direct CJS -> SLIM transform, so any CJS module will be converted to AMD by this transform first :(

**Comment by m-mujica** [comment]
flag 😞 ?

**Comment by matthewp** [comment]
Haha, yeah, flag.

**Comment by m-mujica** [comment]
without the flag, this is the slim output for a cjs module with this branch..... 🙀 😿 

```js
[
    'cjs',
    function (stealRequire, stealExports, stealModule) {
        stealExports.action = function () {
            console.log(`hello world`);
        };
        var module = stealRequire('module');
        stealRequire('a');
        stealRequire('b');
        var a = stealRequire('a'), b = stealRequire('b');
    }
];
```

**Comment by matthewp** [comment]
woops!

**Comment by m-mujica** [comment]
@matthewp tooks a slightly different approach this time, since the feature is under a flag I made it so most of the tests keep the original shape and only a few do set the flag. 

It should be ok now, any concern with the logic I added in the main module to set the flag when there is a direct CJS -> AMD (last) transform?

**Comment by matthewp** [comment]
Lgtm

**Pull request merged**
