### PR TITLE
Support globals configuration

### LINKED ISSUE #62: Support globals configuration
Might need to change the global transpilation to support it.

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #62

### CODE REVIEW

**Comment by matthewp** [comment]
Note, that since this changes how prepareGlobals is called to only work with a newer version of Steal, this will mean a major version bump to transpile.

**Comment by m-mujica** [comment]
@matthewp

**Comment by matthewp** [comment]
👍

**Comment by matthewp** [comment]
This needs to be 2.0

**Pull request merged**
