### PR TITLE
Add AMD -> SLIM transpiler

### PR DESCRIPTION
**Pull request by m-mujica**
- [x] Anonymous AMD with no deps
- [x] Anonymous AMD with deps
- [x] Named AMD with no deps 
- [x] Named AMD with deps
- [x] Dynamic imports
- [x] Module ids (normalize)

### CODE REVIEW

**Comment by m-mujica** [comment]
@matthewp I made some progress with the amd->slim transpiler we talked earlier today, in the tests you can see the cases I've covered so far... If you have early feedback that would be cool :D

**Comment by matthewp** [comment]
Not much to say, looks really good!

**Comment by m-mujica** [comment]
Just pushed an update:

- Moved the AST transform helpers into their own module and "lib/amd/slim_builders"
- Added code to handle more AMD variations (named with deps and object shorthand)
- Added logic to transform AMD factory `return` into slim `stealModule.exports` 💥 
- Refactored the AST transform logic, the function takes now the dependencies node and the factory function node and figures what to do. The AST walker's concern is to collect the dependencies/factory and pass it to the `makeAst` function.

This version should be enough to get working an example without dynamic loading, I need to take care of the module ids normalize first. Currently is using steal's module ids. 

🚼

**Comment by m-mujica** [comment]
@matthewp the dynamic imports are being transformed now, see https://github.com/stealjs/transpile/pull/77/files#diff-957fbe02d9002a38b310f175fdba42b3 also the "slim" transpiler uses `normalize` or `normalizeMap  if provided. 

Next step is to integrate this with steal-tools and start testing with some example code. (maybe a pre-release?)

I'll probably ping you to talk about how to solve the bundle ids thing, currently the slim transpiler expects the id to be passed in https://github.com/stealjs/transpile/pull/77/files#diff-0f715189dfb1fe907aa8e03bb208503aR12 but I don't think that will work since transpile happens before bundles are created. 

The code has changed quite a bit, I don't expect any major changes to happen, except maybe more inline docs. If you can take a look again that'd be cool.

**Comment by m-mujica** [comment]
- [ ] Transpile AMD simplified cjs wrapping https://github.com/amdjs/amdjs-api/blob/master/AMD.md#simplified-commonjs-wrapping- (didn't realize the cjs -> amd used this "amd - cjs" format)

**Comment by matthewp** [comment]
@m-mujica make sure to create an issue for global -> slim, if you haven't already.

**Comment by matthewp** [comment]
👍 assuming this works now?

**Comment by m-mujica** [comment]
I have a couple of changes locally that need to submit.

**Pull request merged**
